name: action
description: A new Flutter project.
publish_to: none
version: 0.1.4
environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: null
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
flutter:
  uses-material-design: true
