name: Upgrade Pubspec Version
on:
  workflow_run:
    workflows: ["Release Draft"]
    types:
      - completed

#  release:
#    branches:
#      - main
#    types: [created, edited]

jobs:
#  check-for-draft-release:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: cardinalby/git-get-release-action@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          tag: '1.2.3'
  bump-version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Bumping version'
      - run: echo ${{ jobs.draft-release.outputs.tag }}
#      - uses: actions/checkout@v3
#      - name: Create Pull Request to bump version in pubspec.yaml
#        uses: peter-evans/create-pull-request@v5
#      - uses: pocket-apps/action-update-version@v1
#        with:
#          files: pubspec.yaml
#          version-regexp: '\d+.\d+.\d+'
#          repo-token: ${{ secrets.GITHUB_TOKEN }}