name: Upgrade Pubspec Version
on:
  release:
    branches:
      - main
    types: [created, edited]

jobs:
  bump-version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Bumping version'
      - run: echo ${{ jobs.draft-release.output.tag_name }}
#      - uses: actions/checkout@v3
#      - name: Create Pull Request to bump version in pubspec.yaml
#        uses: peter-evans/create-pull-request@v5
#      - uses: pocket-apps/action-update-version@v1
#        with:
#          files: pubspec.yaml
#          version-regexp: '\d+.\d+.\d+'
#          repo-token: ${{ secrets.GITHUB_TOKEN }}