name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  analyze: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
      - run: flutter --version
      - uses: actions/checkout@v3
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@v2.0.0
        with:
          fatal-infos: true
          fatal-warnings: true