name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  analyze: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
      - run: flutter --version
      - uses: actions/checkout@v3
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@v2.0.0
        with:
          fatal-infos: true
          fatal-warnings: true