name: Release Draft
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited


  push:
    branches:
      - main

permissions: write-all

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  draft-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-output.outputs.tag }}
      url: ${{ steps.set-output.outputs.url }}
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.release-drafter.outputs.tag_name }}
      - name: Set output
        id: set-output
        run: |
          echo "tag='${{ steps.release-drafter.outputs.tag_name }}'" >> $GITHUB_OUTPUT
          echo "url='${{ steps.release-drafter.outputs.html_url }}'" >> $GITHUB_OUTPUT
  bump-version-pr:
    permissions: write-all
    needs: draft-release
    runs-on: ubuntu-latest
    if: |
      contains(needs.draft-release.outputs.url, 'untagged') && 
      github.event.action != 'opened' && 
      github.event.action != 'edited' && 
      github.event.action != 'reopened' && 
      github.ref_name != 'bump-pubspec-version'
    env:
      TAG: ${{ needs.draft-release.outputs.tag }}
    steps:
      - run: echo ${{ github.ref_name }}
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Bump version
        uses: mikefarah/yq@master
        with:
          cmd: |
            tag=${{ env.TAG }}
            version=$(echo "$tag" | sed "s/[[:alpha:]]//g") yq -i '.version = env(version)' pubspec.yaml
      - name: Create Pull Request to bump version in pubspec.yaml
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: "bump-pubspec-version"
          base: main
          commit-message: "build: bump pubspec version to ${{ env.TAG }}"
          title: "build: bump pubspec version to ${{ env.TAG }}"
          labels: "bump-pubspec-version"
          reviewers: "davidnwaneri"
          assignees: "davidnwaneri"
