name: Release Draft
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  semantic-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  draft-release:
    needs: semantic-pull-request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
