name: Release Draft
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited


  push:
    branches:
      - main

permissions: write-all

jobs:
  semantic-pull-request:
#    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  draft-release:
#    needs: [semantic-pull-request]
#    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-output.outputs.tag }}
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.release-drafter.outputs.tag_name }}
#      - run: echo ${{ steps.release-drafter.outputs.tag }}
      - run: echo "::set-output name=tag::'${{ steps.release-drafter.outputs.tag_name }}'"
        id: set-output
  log:
    needs: draft-release
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.draft-release.outputs.tag }}


#  changelog:
##    name: Conventional Changelog Action
#    needs: semantic-pull-request
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#      - run: echo ${{ github.ref }}
#      - uses: "TriPSs/conventional-changelog-action@v3"
#        with:
#          github-token: ${{ secrets.github_token }}
##          git-message: 'chore(release): {version}'
##          git-user-name: 'Awesome Changelog Action'
##          git-user-email: 'awesome_changelog@github.actions.com'
##          preset: 'angular' # default
##          tag-prefix: 'v' # default
##          output-file: CHANGELOG.md # default
#          release-count: '0'
#          version-file: ./pubspec.yaml
##          version-path: 'version' # default
#          skip-on-empty: false
##          skip-version-file: false # default
##          skip-commit: false # default
##          git-branch: main